[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.3",
    "django-widget-tweaks>=1.5.1",
    "openpyxl>=3.1.5",
    "python-dotenv>=1.1.0",
    "reportlab>=4.4.10",
    "uvicorn>=0.48.0",
]
